### ISSUE TITLE
Anything I can do to help?  Analyse and include more words?

### ISSUE THREAD

**Issue by Gleoman** [quadrismegistus/prosodic#25]
I just came across this application the other week and have found it enormously helpful in my own writing.

It's a wonderful piece of kit and should contribute significantly to a lot of really fun poetry.

I noticed that there are a few words that I have tried to process that are not being properly analysed so I was wondering if I might be able to help with that?

For instance, beauty is one and another is unfurls.

**Comment by quadrismegistus** [comment]
Thanks for your comment and sorry to take an eternity to respond. You're right, the orthography tokenizer was making an error on those words. I think I've fixed it now if you want to try with the latest:

```pip install -U prosodic```

```python
import prosodic as p
t=p.Text("beauty unfurls")
# 000001	beauty              	P:'bjuː.tiː                        	S:PU	W:HH
# 000002	?unfurls            	P:                                 	S:?	W:

for w in t.words(): print(w.sylls_text)
# ['bea', 'uty']
# ['un', 'furls']
```

Also, I highly recommend installing espeak so that unknown words can be 'sounded out' for their pronunciation: https://github.com/quadrismegistus/prosodic#setting-up-espeak

For Mac, I do: ```brew install espeak```

Then, the same code will output:

```
000001	beauty              	P:'bjuː.tiː                        	S:PU	W:HH
000002	unfurls             	P:ʌn.'fəːlz                        	S:UP	W:HL
```

Hope this helps. Please update your prosodic beforehand because I actually found a bug while writing this response.


```pip install -U prosodic```

**Comment by quadrismegistus** [comment]
As for what else we can do: anything! I'm keen to add more languages, if you're familiar with any other languages and whether they have a pronunciation dictionary in IPA format somewhere? espeak also handles other languages I believe, so we could work to generalize how espeak and languages work in prosodic: http://espeak.sourceforge.net/languages.html

Also, check out https://github.com/quadrismegistus/cadence too where I'm trying to clean up some of prosodic's code and allow access to its data more easily.
