### ISSUE TITLE
Can't install it

### ISSUE THREAD

**Issue by sowdowdow** [quadrismegistus/prosodic#26]
```bash
pip install git+git://github.com/quadrismegistus/prosodic.
git
Collecting git+git://github.com/quadrismegistus/prosodic.git
  Cloning git://github.com/quadrismegistus/prosodic.git to c:\users\xxx\appdata\local\temp\pip-req-build-s0719i
ak
  Running command git clone -q git://github.com/quadrismegistus/prosodic.git 'C:\Users\xxx\AppData\Local\Temp\p
ip-req-build-s0719iak'
  Running command git submodule update --init --recursive -q
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\xxx\pycharmprojects\prosodicstresses\venv\scripts\python.exe' -c 'import sys, setuptool
s, tokenize; sys.argv[0] = '"'"'C:\\Users\\xx\\AppData\\Local\\Temp\\pip-req-build-s0719iak\\setup.py'"'"'; __
file__='"'"'C:\\Users\\xx\\AppData\\Local\\Temp\\pip-req-build-s0719iak\\setup.py'"'"';f=getattr(tokenize, '"'
"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __f
ile__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\xx\AppData\Local\Temp\pip-pip-egg-info-66a5w1hj'
         cwd: C:\Users\xx\AppData\Local\Temp\pip-req-build-s0719iak\
    Complete output (9 lines):
    C:\Users\xx\AppData\Local\Temp\pip-req-build-s0719iak\setup.py:20: DeprecationWarning: the imp module is d
eprecated in favour of importlib; see the module's documentation for alternative uses
      import sys,os,imp
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\xx\AppData\Local\Temp\pip-req-build-s0719iak\setup.py", line 39, in <module>
        long_description = fh.read()
      File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 11140: character maps to <undefined>
    ----------------------------------------
WARNING: Discarding git+git://github.com/quadrismegistus/prosodic.git. Command errored out with exit status 1: py
thon setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by quadrismegistus** [comment]
Hm, what version of Python are you running? I can't replicate the error. Are you accidentally using python2, or python2's pip?

**Comment by CubieDev** [comment]
@quadrismegistus 
Hello,

I have ran into this issue before when installing as well. 

### How to replicate
- Create a new folder somewhere for testing. We'll delete this folder afterwards.
- Open a terminal, `cd` to the new folder, and run ```python -m venv .env```. I used Python 3.7.9, but this works with 3.8 too I believe. This command will create a virtualenvironment in the new `.env` folder.
- Run ```.\.env\Scripts\Activate.ps1``` to activate the virtualenvironment. (This might differ slightly on Linux. I'm using Windows)
- Now your terminal line will be prepended with `(.env)`. All `python` and `pip` uses will refer to Python in the virtualenvironment.
- You can confirm this by running ```pip freeze```. You'll see that nothing is returned, because no modules are installed on this virtualenvironment.
- Now run ```pip install prosodic```
Exactly the error described by @sowdowdow will pop up.

### Cause of the error
The issue comes from this line in your `setup.py`:
https://github.com/quadrismegistus/prosodic/blob/83b9fc1010c3f4f44e9dc26f98f16b1fc6856ce5/setup.py#L38
It will open the `README.md` and use it as the `long_description` for your PyPI. This is fairly standard, with one exception: Your `README.md` contains (many) difficult "non-default" characters. 
In order to read this file, the `open()` function should be told which encoding has to be used. If this is not done, the error described above pops up.

### The Fix
Replacing the line
https://github.com/quadrismegistus/prosodic/blob/83b9fc1010c3f4f44e9dc26f98f16b1fc6856ce5/setup.py#L38
with 
```python
        with open("README.md", "r", encoding="utf8") as fh:
```
will resolve the issue.

### Workaround I used
I have used your work for my recent project https://github.com/CubieDev/Inflexion. For this project I use GitHub actions to automatically run my tests whenever I push changes. However, to do so, I must first install prosodic. My workaround of this issue was to `git clone` prosodic, rather than `pip install` it. Then I replace the line like explained above, and install it directly from the directory with `pip setup.py install`, and I clean everything up again:
https://github.com/CubieDev/Inflexion/blob/1a392a0d65b5ec7739486d587720fd667e0ce39b/.github/workflows/python-package.yml#L32-L42

Obviously this workaround is far from ideal. 
Instead, I recommend merging the pull request I'll make for this. Note that your `setup.py` is outdated in other ways too. For example, I get the following warning as well:
```python
setup.py:20: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import sys,os,imp
```
I tend to see `importlib` used, but you use some functionality from `imp` for which I haven't been able to find a direct 1-1 replacement for in `importlib`, so I won't touch that.

- Tom Aarsen
